import assert from "node:assert/strict";
import test from "node:test";

import {
  buildCurrentBarDecisionSave,
  markDecisionSubmissionAsManuallyEdited,
} from "../app/features/training/decisionController.ts";

const decision = {
  marketState: "突破模式",
  location: "回调位置",
  reasons: ["顺势", "贴近 EMA"],
  stop: "1.05198",
  target: "1.05640",
  note: "等待再次确认。",
};

test("manual edits turn an automatic plan into a valid manual submission", () => {
  const automaticSubmission = {
    id: "auto-plan",
    barTimestamp: 10,
    cursor: 3,
    referencePrice: 1.05434,
    decision,
    submittedAt: "2026-08-20T00:00:00.000Z",
    autoGenerated: true,
  };

  const updated = markDecisionSubmissionAsManuallyEdited(automaticSubmission, {
    ...decision,
    note: "人工补充了等待条件。",
  });

  assert.equal(updated.id, "auto-plan");
  assert.equal(updated.barTimestamp, 10);
  assert.equal(updated.autoGenerated, false);
  assert.equal(updated.decision.note, "人工补充了等待条件。");
});

test("saving the current-bar plan keeps the replay cursor in place", () => {
  const result = buildCurrentBarDecisionSave({
    existingAutoSubmission: {
      id: "auto-plan",
      autoGenerated: true,
    },
    fallbackId: "manual-plan",
    barTimestamp: 10,
    cursor: 3,
    referencePrice: 1.05434,
    decision,
    submittedAt: "2026-08-20T00:00:00.000Z",
  });

  assert.equal(result.submission.id, "auto-plan");
  assert.equal(result.submission.autoGenerated, false);
  assert.equal(result.replacedAutoGenerated, true);
  assert.equal(result.advancesReplay, false);
});
