import assert from "node:assert/strict";
import test from "node:test";

import {
  buildSopProfileViews,
  evaluateSopGate,
  findSopProfile,
} from "../app/features/sop/sopController.ts";

const completeDecision = {
  marketState: "上升趋势",
  location: "突破回踩关键位置",
  reasons: ["顺势", "信号 K 确认"],
  stop: "100",
  target: "110",
  note: "失效后退出，不追价。",
};

const baseGateInput = {
  strictModeEnabled: true,
  requirePretradePlan: true,
  sopCheckEnabled: true,
  requiredPretradeFields: ["marketState", "location", "reasons", "stop", "target"],
  market: "US",
  instrumentId: "AAPL",
  timeframe: "1d",
  currentTimestamp: 10,
  decision: completeDecision,
  submissions: [],
};

test("strict mode off never blocks an opening order", () => {
  const result = evaluateSopGate({ ...baseGateInput, strictModeEnabled: false });

  assert.equal(result.allowed, true);
  assert.equal(result.status, "off");
});

test("requires a manual pre-trade plan on the current bar", () => {
  const result = evaluateSopGate(baseGateInput);

  assert.equal(result.allowed, false);
  assert.equal(result.status, "blocked");
  assert.equal(result.checks.find((check) => check.id === "pretrade-plan")?.status, "fail");
  assert.match(result.message, /事前规划卡/);
});

test("automatic and backfilled submissions do not satisfy the pre-trade gate", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    submissions: [
      { id: "auto", barTimestamp: 10, autoGenerated: true, decision: completeDecision },
      { id: "backfill", barTimestamp: 10, backfilled: true, decision: completeDecision },
    ],
  });

  assert.equal(result.allowed, false);
  assert.equal(result.checks.find((check) => check.id === "pretrade-plan")?.status, "fail");
});

test("SOP check blocks an incomplete structured plan", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    decision: { ...completeDecision, reasons: ["顺势"], target: "" },
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, false);
  assert.equal(result.checks.find((check) => check.id === "plan-completeness")?.status, "fail");
});

test("configured pre-trade fields can block independently from the SOP check", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    sopCheckEnabled: false,
    requiredPretradeFields: ["marketState", "location", "reasons", "stop", "target"],
    decision: { ...completeDecision, target: "" },
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, false);
  assert.equal(result.checks.find((check) => check.id === "pretrade-plan-fields")?.status, "fail");
  assert.equal(result.checks.find((check) => check.id === "plan-completeness"), undefined);
});

test("turning off one pre-trade field no longer blocks when SOP check is off", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    sopCheckEnabled: false,
    requiredPretradeFields: ["marketState", "location", "reasons", "stop"],
    decision: { ...completeDecision, target: "" },
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, true);
  assert.equal(result.status, "pass");
  assert.equal(result.checks.find((check) => check.id === "pretrade-plan-fields")?.status, "pass");
});

test("SOP completeness remains independent of selected pre-trade fields", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    requiredPretradeFields: ["marketState", "location", "reasons", "stop"],
    decision: { ...completeDecision, target: "" },
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, false);
  assert.equal(result.checks.find((check) => check.id === "pretrade-plan-fields")?.status, "pass");
  assert.equal(result.checks.find((check) => check.id === "plan-completeness")?.status, "fail");
});

test("a complete current-bar manual plan passes the applicable SOP", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, true);
  assert.equal(result.status, "pass");
  assert.equal(result.profile?.id, "us-daily");
  assert.ok(result.checks.every((check) => check.status === "pass"));
});

test("markets without a current SOP remain usable with a visible warning", () => {
  const result = evaluateSopGate({
    ...baseGateInput,
    market: "GOLD",
    instrumentId: "XAUUSD",
    timeframe: "1h",
    submissions: [{ id: "manual", barTimestamp: 10, decision: completeDecision }],
  });

  assert.equal(result.allowed, true);
  assert.equal(result.status, "warning");
  assert.equal(result.profile, null);
});

test("profile statistics are aggregated independently for the three SOP versions", () => {
  const views = buildSopProfileViews([
    { market: "US", timeframe: "1d", result: 2, hasPretradePlan: true, planScore: 100 },
    { market: "US", timeframe: "1d", result: -1, hasPretradePlan: false, planScore: 45 },
    { market: "CN", timeframe: "1d", result: 0.5, hasPretradePlan: true, planScore: 85 },
  ]);

  const us = views.find((profile) => profile.id === "us-daily");
  const fx = views.find((profile) => profile.id === "eurusd-5m");
  assert.equal(us?.sampleCount, 2);
  assert.equal(us?.winRate, 50);
  assert.equal(us?.completePlanRate, 50);
  assert.equal(fx?.sampleCount, 0);
  assert.equal(findSopProfile("FX", "EURUSD.FX", "5m")?.id, "eurusd-5m");
});
