export type DecisionSubmissionRecord<TDecision> = {
  id: string;
  barTimestamp: number;
  cursor: number;
  referencePrice: number;
  decision: TDecision;
  submittedAt: string;
  autoGenerated?: boolean;
};

export function markDecisionSubmissionAsManuallyEdited<TDecision>(
  submission: DecisionSubmissionRecord<TDecision>,
  decision: TDecision,
): DecisionSubmissionRecord<TDecision> {
  return {
    ...submission,
    decision,
    autoGenerated: false,
  };
}

export function buildCurrentBarDecisionSave<TDecision>({
  existingAutoSubmission,
  fallbackId,
  barTimestamp,
  cursor,
  referencePrice,
  decision,
  submittedAt,
}: {
  existingAutoSubmission?: Pick<DecisionSubmissionRecord<TDecision>, "id" | "autoGenerated">;
  fallbackId: string;
  barTimestamp: number;
  cursor: number;
  referencePrice: number;
  decision: TDecision;
  submittedAt: string;
}) {
  return {
    submission: {
      id: existingAutoSubmission?.id ?? fallbackId,
      barTimestamp,
      cursor,
      referencePrice,
      decision,
      submittedAt,
      autoGenerated: false,
    },
    replacedAutoGenerated: Boolean(existingAutoSubmission?.autoGenerated),
    advancesReplay: false as const,
  };
}
