import {
  SOP_PROFILES,
  type SopDecision,
  type SopGateCheck,
  type SopGateInput,
  type SopGateResult,
  type SopMarketCode,
  type SopProfile,
  type SopProfileView,
  type SopSubmission,
  type SopTradeSample,
} from "./sopContracts.ts";
import {
  defaultRequiredPretradeFields,
  pretradePlanFieldOptions,
  type PretradePlanField,
} from "../../lib/tradingDiscipline.ts";

function normalizedText(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

export function normalizeSopMarket(market: string | undefined, instrumentId = ""): SopMarketCode | null {
  const normalized = normalizedText(market).toUpperCase();
  if (normalized === "CN" || normalized === "A股" || /\.(SH|SZ|BJ)$/i.test(instrumentId)) return "CN";
  if (normalized === "US" || normalized === "美股") return "US";
  if (normalized === "FX" || normalized === "FOREX" || normalized === "外汇" || /\.FX$/i.test(instrumentId)) return "FX";
  return null;
}

export function findSopProfile(
  market: string | undefined,
  instrumentId: string,
  timeframe: string,
): SopProfile | null {
  const marketCode = normalizeSopMarket(market, instrumentId);
  return SOP_PROFILES.find((profile) => profile.market === marketCode && profile.timeframe === timeframe) ?? null;
}

function percentage(value: number, total: number) {
  if (!total) return 0;
  return Math.round(value / total * 1000) / 10;
}

export function buildSopProfileViews(samples: SopTradeSample[]): SopProfileView[] {
  return SOP_PROFILES.map((profile) => {
    const profileSamples = samples.filter((sample) => (
      findSopProfile(sample.market, sample.instrumentId ?? "", sample.timeframe)?.id === profile.id
    ));
    const winCount = profileSamples.filter((sample) => sample.result > 0).length;
    const completePlanCount = profileSamples.filter((sample) => sample.hasPretradePlan && sample.planScore >= 80).length;
    const totalResult = profileSamples.reduce((sum, sample) => sum + (Number.isFinite(sample.result) ? sample.result : 0), 0);
    return {
      ...profile,
      sampleCount: profileSamples.length,
      winCount,
      winRate: percentage(winCount, profileSamples.length),
      completePlanCount,
      completePlanRate: percentage(completePlanCount, profileSamples.length),
      averageResult: profileSamples.length ? totalResult / profileSamples.length : 0,
    };
  });
}

function hasManualCurrentPlan(submissions: SopSubmission[], timestamp: number) {
  return submissions.some((submission) => (
    submission.barTimestamp === timestamp
    && !submission.autoGenerated
    && !submission.backfilled
  ));
}

function decisionIsStructured(decision: SopDecision) {
  return Boolean(
    normalizedText(decision.marketState)
    && normalizedText(decision.location)
    && Array.isArray(decision.reasons)
    && decision.reasons.filter((reason) => normalizedText(reason)).length >= 2
    && normalizedText(decision.stop)
    && normalizedText(decision.target),
  );
}

function missingPretradeFields(decision: SopDecision, fields: readonly PretradePlanField[]) {
  return fields.filter((field) => {
    if (field === "reasons") {
      return !Array.isArray(decision.reasons)
        || decision.reasons.filter((reason) => normalizedText(reason)).length < 2;
    }
    return !normalizedText(decision[field]);
  });
}

function pretradeFieldLabel(field: PretradePlanField) {
  return pretradePlanFieldOptions.find((option) => option.key === field)?.label ?? field;
}

function check(
  id: SopGateCheck["id"],
  label: string,
  status: SopGateCheck["status"],
  required: boolean,
  detail: string,
): SopGateCheck {
  return { id, label, status, required, detail };
}

export function evaluateSopGate(input: SopGateInput): SopGateResult {
  const profile = findSopProfile(input.market, input.instrumentId, input.timeframe);
  if (!input.strictModeEnabled) {
    return {
      allowed: true,
      status: "off",
      profile,
      checks: [],
      message: "严格模式未开启，当前开仓流程保持原有行为。",
    };
  }

  const checks: SopGateCheck[] = [];
  const hasPlan = hasManualCurrentPlan(input.submissions, input.currentTimestamp);
  checks.push(check(
    "pretrade-plan",
    "事前规划卡",
    hasPlan ? "pass" : input.requirePretradePlan ? "fail" : "warn",
    input.requirePretradePlan,
    hasPlan
      ? "当前 K 线已有手动提交的事前规划卡。"
      : input.requirePretradePlan
        ? "请先在当前 K 线上提交事前规划卡；自动关联保护价和补写记录不算事前计划。"
        : "未要求事前规划卡，当前只记录为草稿。",
  ));

  if (input.requirePretradePlan) {
    const missingFields = missingPretradeFields(
      input.decision,
      input.requiredPretradeFields ?? defaultRequiredPretradeFields,
    );
    checks.push(check(
      "pretrade-plan-fields",
      "规划卡必填项",
      missingFields.length ? "fail" : "pass",
      true,
      missingFields.length
        ? `请补齐规划卡必填项：${missingFields.map(pretradeFieldLabel).join("、")}。`
        : "规划卡必填项已填写。",
    ));
  }

  if (!input.sopCheckEnabled) {
    checks.push(check("sop-profile", "SOP 版本", profile ? "pass" : "warn", false, profile ? `${profile.title} ${profile.version}` : "当前市场暂无适用 SOP 版本。"));
  } else if (!profile) {
    checks.push(check("sop-profile", "SOP 版本", "warn", false, "当前市场暂无适用 SOP 版本，本次只执行其他已开启的门禁。"));
  } else {
    checks.push(check("sop-profile", "SOP 版本", "pass", true, `匹配 ${profile.title} ${profile.version}。`));
    checks.push(check(
      "plan-completeness",
      "结构化计划",
      decisionIsStructured(input.decision) ? "pass" : "fail",
      true,
      decisionIsStructured(input.decision)
        ? "市场状态、位置、至少两个理由、失效点和第一目标均已填写。"
        : "请补齐市场状态、位置、至少两个交易理由、失效点和第一目标。",
    ));
  }

  const failed = checks.filter((item) => item.required && item.status === "fail");
  const warnings = checks.filter((item) => item.status === "warn");
  if (failed.length) {
    return {
      allowed: false,
      status: "blocked",
      profile,
      checks,
      message: failed.map((item) => item.detail).join("；"),
    };
  }
  if (warnings.length) {
    return {
      allowed: true,
      status: "warning",
      profile,
      checks,
      message: `${profile ? "严格模式检查通过。" : "严格模式已执行。"}${warnings.map((item) => item.detail).join("；")}`,
    };
  }
  return {
    allowed: true,
    status: "pass",
    profile,
    checks,
    message: "严格模式检查通过，可以提交开仓委托。",
  };
}

export { SOP_PROFILES } from "./sopContracts.ts";
export type { SopProfileView } from "./sopContracts.ts";
