import type { PretradePlanField } from "../../lib/tradingDiscipline.ts";

export type SopProfileId = "us-daily" | "cn-daily" | "eurusd-5m";
export type SopMarketCode = "US" | "CN" | "FX";

export type SopRule = {
  id: string;
  label: string;
  description: string;
  required: boolean;
};

export type SopProfile = {
  id: SopProfileId;
  version: string;
  market: SopMarketCode;
  marketLabel: string;
  timeframe: string;
  title: string;
  subtitle: string;
  thesis: string;
  rules: SopRule[];
  guardrails: string[];
};

export type SopTradeSample = {
  market: string;
  instrumentId?: string;
  timeframe: string;
  result: number;
  hasPretradePlan: boolean;
  planScore: number;
};

export type SopProfileView = SopProfile & {
  sampleCount: number;
  winCount: number;
  winRate: number;
  completePlanCount: number;
  completePlanRate: number;
  averageResult: number;
};

export type SopDecision = {
  marketState?: string;
  location?: string;
  reasons?: string[];
  stop?: string;
  target?: string;
  note?: string;
};

export type SopSubmission = {
  barTimestamp: number;
  decision?: SopDecision;
  autoGenerated?: boolean;
  backfilled?: boolean;
};

export type SopGateInput = {
  strictModeEnabled: boolean;
  requirePretradePlan: boolean;
  requiredPretradeFields: PretradePlanField[];
  sopCheckEnabled: boolean;
  market: string;
  instrumentId: string;
  timeframe: string;
  currentTimestamp: number;
  decision: SopDecision;
  submissions: SopSubmission[];
};

export type SopGateCheckStatus = "pass" | "fail" | "warn";

export type SopGateCheck = {
  id: "pretrade-plan" | "pretrade-plan-fields" | "sop-profile" | "plan-completeness";
  label: string;
  status: SopGateCheckStatus;
  required: boolean;
  detail: string;
};

export type SopGateResult = {
  allowed: boolean;
  status: "off" | "pass" | "blocked" | "warning";
  profile: SopProfile | null;
  checks: SopGateCheck[];
  message: string;
};

export const SOP_PROFILES: readonly SopProfile[] = [
  {
    id: "us-daily",
    version: "v1.0",
    market: "US",
    marketLabel: "美股",
    timeframe: "1d",
    title: "美股日线版",
    subtitle: "趋势延续与突破回踩",
    thesis: "只在日线方向和位置同时清楚时出手，避免把波动当成信号。",
    rules: [
      { id: "direction", label: "方向先行", description: "先标出日线趋势、突破方向或明确的反转边界。", required: true },
      { id: "location", label: "位置可解释", description: "入场应靠近关键支撑阻力、突破回踩或趋势回撤，不在区间正中追价。", required: true },
      { id: "trigger", label: "触发确认", description: "等待信号 K 线或二次入场确认，计划中写清楚什么会触发执行。", required: true },
      { id: "risk", label: "风险先定", description: "入场前写好失效点与第一目标，先计算风险再决定仓位。", required: true },
    ],
    guardrails: ["不追离关键位置过远的加速段", "财报或重大事件前后单独标记，不混入普通样本"],
  },
  {
    id: "cn-daily",
    version: "v1.0",
    market: "CN",
    marketLabel: "A 股",
    timeframe: "1d",
    title: "A 股日线版",
    subtitle: "趋势位置与交易规则",
    thesis: "先判断结构，再把涨跌停、T+1 和流动性约束纳入计划。",
    rules: [
      { id: "structure", label: "结构清楚", description: "确认趋势、突破或趋势回调，不把单根放量 K 线直接当成趋势。", required: true },
      { id: "location", label: "位置清楚", description: "说明价格位于支撑、阻力、突破回踩还是区间中部。", required: true },
      { id: "reason", label: "至少两个理由", description: "理由要能回看验证，例如顺势、关键位置、信号 K 确认或失败突破。", required: true },
      { id: "execution", label: "规则可执行", description: "写明失效点、第一目标，并预先考虑 T+1 与价格限制。", required: true },
    ],
    guardrails: ["买入当日不假设可以卖出", "涨跌停、停牌和流动性异常时降低样本权重"],
  },
  {
    id: "eurusd-5m",
    version: "v1.0",
    market: "FX",
    marketLabel: "EURUSD",
    timeframe: "5m",
    title: "EURUSD 5 分钟版",
    subtitle: "高周期背景与盘中触发",
    thesis: "5 分钟只负责找执行点，方向和位置必须先由更高周期约束。",
    rules: [
      { id: "context", label: "先看高周期", description: "先记录 1h/15m 的方向、区间边界和当天主要交易时段。", required: true },
      { id: "location", label: "等待位置", description: "只在区间边界、趋势回撤或突破回踩附近寻找 5 分钟机会。", required: true },
      { id: "trigger", label: "等待触发", description: "用信号 K、二次入场或失败突破确认，不在中间位置猜方向。", required: true },
      { id: "risk", label: "点差与风险", description: "写好止损、第一目标和风险金额，点差异常时放弃交易。", required: true },
    ],
    guardrails: ["避开重大数据公布前后的随机波动", "没有高周期背景时，5 分钟形态只记为观察样本"],
  },
] as const;
